### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by janisblaus** [QuentinCG/GSM-TC35-Python-Library#11]
Hi Quentin, 

Super useful library! I'm loving it!

One issue that I did not manage to resolve - when I try to send 

`Python GSMTC35.py --serialPort COM3 --sendSpecialSMS +37125502235 "Hello Jānis"`

I receive unreadable characters on my phone. 

For tests, I'm using windows 10, Python 3.7

Is it possible to resolve this somehow?

**Comment by QuentinCG** [comment]
Hi Janis,

Strange, sendSpecialSMS should send special char correctly.

Could you try 2 things to better understand the issue:
 - What happens when you send "你好，你是？" to the phone that had bad char ?
 - What happens when you send "Hello Jānis" to an other phone ?

If both fail, could you check if your terminal is UTF8 compliant ?
https://serverfault.com/questions/13898/how-to-find-out-if-a-terminal-supports-utf-8

Cheers
Quentin

**Comment by janisblaus** [comment]
Hi @QuentinCG !

Thank you for such a promt response. 

Here is the result, 

![image](https://user-images.githubusercontent.com/1029697/62424769-143b4600-b6dc-11e9-8307-94273ee97a47.png)

Tested from Ubuntu, Python 3.6.8 and Samsung Galaxy S10 and iPhone 6. Both same results. 

here is the console output:
![image](https://user-images.githubusercontent.com/1029697/62424789-6b411b00-b6dc-11e9-81a6-7255559bdac1.png)

**Comment by janisblaus** [comment]
Perhaps the issue comes from the fact is actually MC35i instead of TC35, I just found out that. 

Although, I have TC35 with my windows machine and same results apply so that's not the case imo. 

Terminal supports utf-8. File is in utf-8 encoding as well.

**Comment by QuentinCG** [comment]
Thank you for your information.

I don't think it is an incompatibility between TC35 and MC35.
As you describe it, it seems to be a bug in the library.
I'll investigate and check what is happening.

**Comment by QuentinCG** [comment]
After discussion with @janisblaus and some investigations on both parts, the "test" branch is now handling utf-8 correctly but the last char is not sent correctly. I'll investigate on this minor issue before merging the fix into master branch.

**Comment by QuentinCG** [comment]
Fixed in master (issue with the "last char" fixed too in master branch)
