### ISSUE TITLE
Pickup Call and save it to audio file

### ISSUE THREAD

**Issue by xcyber02** [QuentinCG/GSM-TC35-Python-Library#21]
hi, can i do someting like pickup call and save it to audio file using this library?
and if that can, would you mind to give me some example how to do it?

thanks

**Comment by QuentinCG** [comment]
Hello @xcyber02 ,
I created this as a base for your need.
You'll still have to implement the audio start recording and stop recording.
Feel free to post your working script here so that I can add it in library example !

examples/pick_up_and_save_audio/
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
  Use GSM module to pick-up call every time someone calls and save the associated audio file:
   - Inialize module
   - In a loop (3sec sleep):
     - Check if call state
     - If in call, hang up
     - If someone is calling:
      - Get the phone number calling
      - Pick up call
      - In a try-catch:
        - Start audio recording (with phone number in parameter)
        - Loop until the call ends or timeout of 5min
        - If still in call after 5min, hang up
        - Stop audio recording
"""
__author__ = 'Quentin Comte-Gaz'
__email__ = "quentin@comte-gaz.com"
__license__ = "MIT License"
__copyright__ = "Copyright Quentin Comte-Gaz (2024)"
__python_version__ = "3.+"
__version__ = "0.1 (2024/08/02)"
__status__ = "Not tested"

from datetime import datetime
import time
import logging
import binascii
import serial

# Relative path to import GSMTC35 (not needed if GSMTC35 installed from pip)
import sys
sys.path.append("../..")

from GSMTC35 import GSMTC35

# ---- Config ----
pin = "1234"
puk = "12345678"
port = "COM8"

# Audio input device name
audio_input_device = "default"

# Audio record base save folder
audio_save_folder = "./audio_records"

# Debug mode
use_debug = True

# ---- App base ----
if use_debug:
  logger = logging.getLogger()
  logger.setLevel(logging.DEBUG)

# ---- Base functions ----
def getGSM():
  """Base function to get initialized GSM class

  return (bool, GSMTC35, string): success, GSM class, error explanation
  """
  gsm = GSMTC35.GSMTC35()

  try:
    if not gsm.isInitialized():
      if not gsm.setup(_port="COM8", _pin=pin, _puk=puk):
        return False, gsm, str("Failed to initialize GSM/SIM")

  except serial.serialutil.SerialException:
    return False, gsm, str("Failed to connect to GSM module")

  return True, gsm, str("")

def check_call_state(gsm):
  """Check the call state and handle accordingly"""
  if gsm.isInCall():
    gsm.hangUp()
  elif gsm.isRinging():
    phone_number = gsm.getCallerNumber()
    handle_incoming_call(gsm, phone_number)

def handle_incoming_call(gsm, phone_number):
  """Handle an incoming call"""
  try:
    # Pick up call
    if gsm.pickUp():
      # Start audio recording
      start_audio_recording(phone_number)
      # Wait for call to end
      try:
        start_time = time.time()
        while gsm.isInCall() and (time.time() - start_time) < 300:
          time.sleep(1)
      except Exception as e:
        logger.error(f"Error handling call: {e}")

      # Hang up call if still in call after 5min
      if gsm.isInCall():
        gsm.hangUp()
  except Exception as e:
    logger.error(f"Error handling call: {e}")
  finally:
    # Stop audio recording
    stop_audio_recording()

def start_audio_recording(phone_number):
  """Start recording audio"""
  timestamp = datetime.now().strftime("%Y-%m-%d %H.%M.%S")
  audio_filename = f"{audio_save_folder}/{timestamp} - {phone_number}.wav"
  # Start audio recording
  logger.info(f"Started recording audio: {audio_filename}")
  # TODO IMPLEMENT START AUDIO RECORDING HERE

def stop_audio_recording():
  """Stop recording audio"""
  logger.info("Stopped recording audio")
  # TODO IMPLEMENT STOP AUDIO RECORDING HERE

# ---- Launch application ----
if __name__ == '__main__':
  success, gsm, error = getGSM()
  if not success:
    logger.error(f"Failed to initialize GSM: {error}")
    sys.exit(1)

  while True:
    try:
      check_call_state(gsm)
      time.sleep(3)
    except KeyboardInterrupt:
      logger.info("Application stopped by user")
      break
    except Exception as e:
      logger.error(f"Unexpected error: {e}")
      time.sleep(5)

```

**Comment by xcyber02** [comment]
hi @QuentinCG, thanks for answering
here's my code
`#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
  Use GSM module to pick-up call every time someone calls and save the associated audio file:
   - Inialize module
   - In a loop (3sec sleep):
     - Check if call state
     - If in call, hang up
     - If someone is calling:
      - Get the phone number calling
      - Pick up call
      - In a try-catch:
        - Start audio recording (with phone number in parameter)
        - Loop until the call ends or timeout of 5min
        - If still in call after 5min, hang up
        - Stop audio recording
"""
__author__ = 'Quentin Comte-Gaz'
__email__ = "quentin@comte-gaz.com"
__license__ = "MIT License"
__copyright__ = "Copyright Quentin Comte-Gaz (2024)"
__python_version__ = "3.+"
__version__ = "0.1 (2024/08/02)"
__status__ = "Not tested"

from datetime import datetime
import time
import logging
import binascii
import serial
import wave
from time import sleep

# Relative path to import GSMTC35 (not needed if GSMTC35 installed from pip)
import sys
sys.path.append("../..")

from GSMTC35 import GSMTC35

# ---- Config ----
pin = "1234"
puk = "12345678"
port = "COM21"

# Audio input device name
audio_input_device = "default"

# Audio record base save folder
audio_save_folder = "C:/Users/sispu/Documents/bot_kartu/audio"

# Debug mode
use_debug = True

# ---- App base ----
if use_debug:
  logger = logging.getLogger()
  logger.setLevel(logging.DEBUG)

# ---- Base functions ----
def getGSM():
  """Base function to get initialized GSM class

  return (bool, GSMTC35, string): success, GSM class, error explanation
  """
  gsm = GSMTC35.GSMTC35()

  try:
    if not gsm.isInitialized():
      if not gsm.setup(_port="COM21"):
        return False, gsm, str("Failed to initialize GSM/SIM")

  except serial.serialutil.SerialException:
    return False, gsm, str("Failed to connect to GSM module")

  return True, gsm, str("")

def check_call_state(gsm):
  """Check the call state and handle accordingly"""
  if gsm.isCallInProgress():
    gsm.hangUp()
  elif gsm.isSomeoneCalling():
    phone_number = gsm.getCurrentCallState()[1]
    handle_incoming_call(gsm, phone_number)

def handle_incoming_call(gsm, phone_number):
  """Handle an incoming call"""
  try:
    # Pick up call
    if gsm.pickUpCall():
      # Start audio recording
      start_audio_recording(phone_number)
      # Wait for call to end
      try:
        start_time = time.time()
        while gsm.isCallInProgress() and (time.time() - start_time) < 300:
          time.sleep(1)
      except Exception as e:
        logger.error(f"Error handling call: {e}")

      # Hang up call if still in call after 5min
      if gsm.isCallInProgress():
        gsm.hangUp()
  except Exception as e:
    logger.error(f"Error handling call: {e}")
  finally:
    # Stop audio recording
    stop_audio_recording()

def start_audio_recording(phone_number):
  """Start recording audio"""
  timestamp = datetime.now().strftime("%Y-%m-%d %H.%M.%S")
  audio_filename = f"{audio_save_folder}/{phone_number}.wav"
  # Start audio recording
  logger.info(f"Started recording audio: {audio_filename}")
  # TODO IMPLEMENT START AUDIO RECORDING HERE
  gsm.close()
  analog_modem = serial.Serial()
  analog_modem.port = "COM21"
  analog_modem.baudrate = 57600 #9600 #115200
  analog_modem.bytesize = serial.EIGHTBITS #number of bits per bytes
  analog_modem.parity = serial.PARITY_NONE #set parity check: no parity
  analog_modem.stopbits = serial.STOPBITS_ONE #number of stop bits
  analog_modem.timeout = 3            #non-block read
  analog_modem.xonxoff = False     #disable software flow control
  analog_modem.rtscts = False     #disable hardware (RTS/CTS) flow control
  analog_modem.dsrdtr = False      #disable hardware (DSR/DTR) flow control
  analog_modem.writeTimeout = 3     #time
  analog_modem.open()
  analog_modem.write(("AT+FCLASS=8").encode())
  analog_modem.write(("AT+VGT=128").encode())
  analog_modem.write(("AT+VSM=128,8000").encode())
  analog_modem.write(("AT+VSD=128,0").encode())
  analog_modem.write(("AT+VLS=1").encode())
  analog_modem.write(("AT+VSD=128,50").encode())
  analog_modem.write(("AT+VTS=[933,900,100]").encode())
  analog_modem.write(("AT+VRX").encode())
  CHUNK = 1024
  audio_frames = []
  count = 1
  target = 10
  while count < target:
    audio_data = analog_modem.read(CHUNK)
    audio_frames.append(audio_data)
    print(audio_frames)
    count = count + 1
  wf = wave.open(audio_filename, 'wb')
  wf.setnchannels(1)
  wf.setsampwidth(1)
  wf.setframerate(8000)
  wf.writeframes(b''.join(audio_frames))
  sleep(10)
  wf.close()
  sleep(10)
  analog_modem.close()
  gsm.setup(_port="COM21")

def stop_audio_recording():
  """Stop recording audio"""
  logger.info("Stopped recording audio")
  # TODO IMPLEMENT STOP AUDIO RECORDING HERE

# ---- Launch application ----
if __name__ == '__main__':
  success, gsm, error = getGSM()
  if not success:
    logger.error(f"Failed to initialize GSM: {error}")
    sys.exit(1)

  while True:
    try:
      check_call_state(gsm)
      time.sleep(3)
    except KeyboardInterrupt:
      logger.info("Application stopped by user")
      break
    except Exception as e:
      logger.error(f"Unexpected error: {e}")
      time.sleep(5)
`
but seems like error, can you help me?

**Comment by xcyber02** [comment]
wow this really helpful, thanks mate 👍

**Comment by QuentinCG** [comment]
@xcyber02 You are welcome.
If you have a fully working script, could you post it here so I add it on examples and add you as contributor on readme ;)
